# For more info on HTTP files go to https://aka.ms/vs/httpfile

@Appointment_HostAddress = http://localhost:5126

### 1. Pobierz wszystkie wizyty
GET {{Appointment_HostAddress}}/api/appointments
Accept: application/json

### 2a. Pobierz wizyty po statusie
GET {{Appointment_HostAddress}}/api/appointments?status=Scheduled
Accept: application/json

### 2b. Pobierz wizyty po nazwisku pacjenta
GET {{Appointment_HostAddress}}/api/appointments?patientLastName=Nowak
Accept: application/json

### 2c. Pobierz wizyty po nazwisku lekarza
GET {{Appointment_HostAddress}}/api/appointments?doctorLastName=Mazur
Accept: application/json


### 3. Pobierz jedn¹ istniej¹c¹ wizytê
GET {{Appointment_HostAddress}}/api/appointments/1
Accept: application/json

### 4. SprawdŸ 404 dla nieistniej¹cej wizyty
GET {{Appointment_HostAddress}}/api/appointments/999999
Accept: application/json

### 5. Dodaj poprawn¹ wizytê
POST {{Appointment_HostAddress}}/api/appointments
Content-Type: application/json

{
  "idPatient": 1,
  "idDoctor": 1,
  "appointmentDate": "2026-12-20T10:30:00",
  "reason": "Control visit"
}

### 6. Dodaj wizytê w przesz³oœci - oczekiwane 400
POST {{Appointment_HostAddress}}/api/appointments
Content-Type: application/json

{
  "idPatient": 1,
  "idDoctor": 1,
  "appointmentDate": "2020-01-01T10:30:00",
  "reason": "Past visit"
}

### 7. Konflikt terminu - oczekiwane 409
POST {{Appointment_HostAddress}}/api/appointments
Content-Type: application/json

{
  "idPatient": 1,
  "idDoctor": 1,
  "appointmentDate": "2026-12-20T10:30:00",
  "reason": "Conflict visit"
}

### 8. Aktualizuj wizytê
PUT {{Appointment_HostAddress}}/api/appointments/1
Content-Type: application/json

{
  "idPatient": 1,
  "idDoctor": 1,
  "appointmentDate": "2026-05-22T12:00:00",
  "status": "Scheduled",
  "reason": "Rescheduled consultation",
  "internalNotes": "Patient asked for a later hour."
}

### 9. Usuñ wizytê
DELETE {{Appointment_HostAddress}}/api/appointments/7
Accept: application/json

### 10a.Usuñ nieistniej¹c¹ wizytê - oczekiwane 404
DELETE {{Appointment_HostAddress}}/api/appointments/999999
Accept: application/json

### 10b.Usuñ wizytê o statusie Scheduled - oczekiwane 409
DELETE {{Appointment_HostAddress}}/api/appointments/4
Accept: application/json